# config
cover: /img/cover1.png
logo: /img/pkq.png
top_saying:
- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: 虽然还没想好写点什么，但是总觉得这里放句话比较和谐。
# Content
excerpt_link: Read More

# rss: /atom.xml

highlightjs: vs

#Works
# works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/TurlingXian
# twitter: https://twitter.com/
# facebook: https://www.facebook.com/
# google: https://google.com/
# weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
# links:
# - name: Kieran
#   link: http://go.kieran.top/
# - name: Name
#   link: http://domain.com/

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2

# live2d public + helper-featured configuration
# live2d:
#   enable: true
#   scriptFrom: local
#   pluginRootPath: live2dw/
#   pluginJsPath: lib/
#   pluginModelPath: assets/
#   tagMode: false
#   debug: false
#   model:
#     use: live2d-widget-model-koharu
#   display:
#     position: right
#     width: 150
#     height: 300
#   mobile:
#     show: true
#     scale: 0.5
#   react:
#     opacity: 0.5
#     opacityDefault: 0.7
#     opacityOnHover: 0.9
